# Generated by Django 4.2.13 on 2024-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_bestsell_options_alter_vegetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsell',
            name='price_type',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Euro')], default='USD', max_length=25),
        ),
        migrations.AlterField(
            model_name='bestsell',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price_type',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Euro')], default='USD', max_length=25),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='price_type',
            field=models.CharField(choices=[('USD', 'Usd'), ('RUB', 'Euro')], default='USD', max_length=25),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
